frontend/package-lock.json, frontend/package.json
=> [releng] Use the latest version of @eclipse-siris/sirius-components

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml
Bug: https://github.com/eclipse-sirius/sirius-components/issues/145
=> [145] Upgrade to Spring Boot 2.4.0

frontend/package-lock.json, frontend/package.json, frontend/src/ApolloGraphQLClient.js, frontend/src/index.js
=> [11] Add support for Apollo client

backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/SpringWebMvcConfigurer.java
Bug: https://github.com/eclipse-sirius/sirius-web/issues/14
=> [14] Fix an issue with our invalid CORS configuration

frontend/package-lock.json, frontend/package.json, frontend/src/index.js
Bug: https://github.com/eclipse-sirius/sirius-components/issues/173
=> [173] Add support for MaterialUI and XState

frontend/package-lock.json, frontend/package.json
Bug: https://github.com/eclipse-sirius/sirius-components/issues/173
Signed-off-by: Florian Barbin <florian.barbin@obeo.fr>
=> [173] Add missing dependencies to fontsource-roboto and xstate-react

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml
Bug: https://github.com/eclipse-sirius/sirius-components/issues/193
=> [193] Move to Spring Boot 2.4.1

.github/workflows/build-sample-app.yml, backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, frontend/package-lock.json, frontend/package.json
=> [releng] Upgrade to Sirius Components 0.1.33

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, backend/sirius-web-sample-application/src/main/resources/db/changelog/schema.sql, frontend/package-lock.json, frontend/package.json, frontend/src/main/Main.tsx
Depends on https://github.com/eclipse-sirius/sirius-components/pull/236, so the build is expected to fail until that is merged.
=> Add support for modelers

.github/workflows/build-sample-app.yml, backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, frontend/package-lock.json, frontend/package.json
Use sirius-components 0.2.0 and bump version to 0.2.0 too.
=> [releng] Move to 0.2.0

backend/sirius-web-sample-application/src/main/resources/db/changelog/schema.sql
=> [fix] Fix constraint on Modeler table

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, frontend/package-lock.json, frontend/package.json
- airbnb-prop-types (we never really used it)
- universal-cookie (we don't even use cookies)
=> [cleanup] Remove useless dependencies

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/services/ProjectAccessPolicy.java, frontend/package-lock.json, frontend/package.json
Nothing meaningful here until the new release of Sirius Components
=> [releng] Upgrade to the latest version of Sirius Components

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, frontend/package-lock.json, frontend/package.json
=> [releng] Upgrade to Sirius Components 0.2.8

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, frontend/package-lock.json, frontend/package.json
=> [releng] Upgrade to Sirius Components 0.2.19

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, backend/sirius-web-sample-application/src/main/resources/application-dev.properties, frontend/package-lock.json, frontend/package.json, frontend/src/main/Main.tsx, frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.module.css, frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx, frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.types.ts, frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbarContextMenu.tsx, frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbarContextMenu.types.ts, frontend/src/views/edit-project/EditProjectNavbar/machine.ts, frontend/src/views/edit-project/EditProjectNavbar/reducer.ts, frontend/src/views/edit-project/EditProjectView.tsx, frontend/src/views/edit-project/EditProjectView.types.ts, frontend/src/views/edit-project/EditProjectViewMachine.ts, frontend/src/views/new-project/NewProjectView.tsx, frontend/src/views/new-project/NewProjectView.types.ts, frontend/src/views/new-project/NewProjectViewMachine.ts, frontend/src/views/projects/ProjectsView.tsx, frontend/src/views/projects/ProjectsView.types.ts, frontend/src/views/projects/ProjectsViewMachine.ts, frontend/src/views/upload-project/UploadProjectView.tsx, frontend/src/views/upload-project/UploadProjectViewMachine.tsx, frontend/tsconfig.json
=> [402] Move the views in Sirius Web

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, frontend/package-lock.json, frontend/package.json, frontend/src/views/new-project/NewProjectView.tsx, frontend/src/views/projects/ProjectsView.tsx, frontend/src/views/upload-project/UploadProjectView.tsx
=> [releng] Switch to Sirius Components 0.2.21

frontend/src/index.tsx
https://github.com/eclipse-sirius/sirius-web/issues/58
It applies sirius-web theme to Material-UI components.
=> Define a Sirius specific theme for Material UI

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, frontend/package-lock.json, frontend/package.json
=> [releng] Switch to Sirius Components 0.2.23

frontend/src/views/projects/ProjectsView.tsx
=> [cleanup] Improve the CSS of the projets view

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml
=> [releng] Update to Spring Boot 2.5.2

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, frontend/package-lock.json, frontend/package.json
=> [releng] Switch to Sirius Components 0.3.4

.github/workflows/build-sample-app.yml, frontend/package.json, frontend/src/ApolloGraphQLClient.tsx, frontend/src/footer/Footer.tsx, frontend/src/index.tsx, frontend/src/navigationBar/Help.tsx, frontend/src/navigationBar/NavigationBar.tsx, frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx, frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbarContextMenu.tsx, frontend/src/views/edit-project/EditProjectNavbar/reducer.ts, frontend/src/views/edit-project/EditProjectView.tsx, frontend/src/views/edit-project/EditProjectViewMachine.ts, frontend/src/views/new-project/NewProjectView.tsx, frontend/src/views/projects/ProjectsView.tsx, frontend/src/views/upload-project/UploadProjectView.tsx, frontend/src/views/upload-project/UploadProjectViewMachine.tsx
Bug: https://github.com/eclipse-sirius/sirius-components/issues/607
=> [607] Format the TypeScript code with Prettier

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, frontend/package-lock.json, frontend/package.json
=> [releng] Switch to Sirius Components 0.3.5

backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/CustomImagesLoader.java
=> [fix] Prevent exception on startup if optional property is not set

backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/StudioConfiguration.java
Bug: https://github.com/eclipse-sirius/sirius-components/issues/557
=> [557] Improve the default View definition

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/StereotypeBuilder.java, frontend/package-lock.json, frontend/package.json
=> [releng] Switch to Sirius Components 0.3.6

backend/sirius-web-frontend/pom.xml, backend/sirius-web-sample-application/pom.xml, frontend/package-lock.json, frontend/package.json, frontend/src/views/edit-project/EditProjectView.tsx
Prevents the application to display a global vertical scrollbar when side views have too much height.
=> [releng] Switch to Sirius Components 0.3.7

backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/services/EditingDomainServicesProvider.java, backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/EditingDomainFactory.java, backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextSearchService.java
bug: https://github.com/eclipse-sirius/sirius-web/issues/113
Signed-off-by: Arthur Daussy <arthur.daussy@obeo.fr>
=> [113] Improve ResourceSet creation to be a IEditingDomainProvider

backend/sirius-web-frontend/pom.xml, backend/sirius-web-graphql-schema/pom.xml, backend/sirius-web-graphql/pom.xml, backend/sirius-web-persistence/pom.xml, backend/sirius-web-sample-application/pom.xml, backend/sirius-web-services-api/pom.xml, backend/sirius-web-services/pom.xml, backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationsDescriptionProvider.java, backend/sirius-web-spring/pom.xml, frontend/package-lock.json, frontend/package.json
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1045
Signed-off-by: Laurent Delaigue <laurent.delaigue@obeo.fr>
=> [1045] Use List<?> instead of List<Object>

backend/sirius-web-frontend/pom.xml, backend/sirius-web-graphql-schema/pom.xml, backend/sirius-web-graphql/pom.xml, backend/sirius-web-persistence/pom.xml, backend/sirius-web-sample-application/pom.xml, backend/sirius-web-services-api/pom.xml, backend/sirius-web-services/pom.xml, backend/sirius-web-spring/pom.xml, frontend/package-lock.json, frontend/package.json
=> [releng] Switch to Sirius Components 2022.01.16

backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/entities/RepresentationEntity.java, backend/sirius-web-persistence/src/main/resources/db/changelog/sirius-web-schema.sql, backend/sirius-web-persistence/src/test/java/org/eclipse/sirius/web/persistence/repositories/RepresentationRepositoryIntegrationTests.java, backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/representations/IRepresentationService.java, backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/representations/RepresentationDescriptor.java, backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/ExplorerDescriptionProvider.java, backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationMapper.java, backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationService.java, backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationsDescriptionProvider.java
- [699] Reduce usage of IRepresentation in favor of RepresentationMetadata
- [699] Store kind and descriptionId in the representation table
=> [699] Improve support for RepresentationMetadata

backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationsRepresentationRefreshPolicyProvider.java
Bug: #205
Signed-off-by: Raphaël Pagé <raphael.page@obeo.fr>
=> [205] Fix representations representation refresh

CHANGELOG.adoc, backend/sirius-web-graphql/pom.xml, backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationAddWidgetDataFetcher.java, backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationDeleteWidgetDataFetcher.java, backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/representation/RepresentationMetadataDataFetcher.java, backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionFormDescriptionEditorEventDataFetcher.java
What is the main goal of this pull request?
- [] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
This section is not relevant if your contribution does not come with changes to the frontend.
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).
- Hooks are properly typed:
This section is not relevant if your contribution does not come with changes to the backend.
_Please describe here the various use cases to test this pull request_
=> [1169] Handle FormDescriptionEditor

backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationMoveWidgetDataFetcher.java
What is the main goal of this pull request?
This section is not relevant if your contribution does not come with changes to the frontend.
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).
- Hooks are properly typed:
This section is not relevant if your contribution does not come with changes to the backend.
_Please describe here the various use cases to test this pull request_
=> [1169] Handle move widget mutation in FormDescriptionEditor
